(function(){
  'use strict';
  const S=window.PBNStudioStorage, palette=window.PALETTE_ITEMS||[];
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  let activeProjectId=S.getActive(), activeVersionId='', currentPreviewSvg='';
  const hexByTag=Object.fromEntries(palette.map(p=>[String(p.tag),String(p.hex).toLowerCase()]));
  const tagByHex=Object.fromEntries(palette.map(p=>[String(p.hex).toLowerCase(),String(p.tag)]));
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
  function toast(msg){const n=document.createElement('div');n.className='toast';n.textContent=msg;document.body.appendChild(n);setTimeout(()=>n.remove(),3200);}
  function dl(name,text,type='text/plain'){const a=document.createElement('a'),blob=new Blob([text],{type});a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2500);}
  function slug(s){return String(s||'design').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'design';}
  function cssHex(v){v=String(v||'').trim().toLowerCase();if(/^#[0-9a-f]{6}$/.test(v))return v;if(/^#[0-9a-f]{3}$/.test(v))return '#'+v.slice(1).split('').map(x=>x+x).join('');const m=v.match(/rgba?\((\d+)[ ,]+(\d+)[ ,]+(\d+)/);if(m)return '#'+[m[1],m[2],m[3]].map(x=>Math.max(0,Math.min(255,+x)).toString(16).padStart(2,'0')).join('');return '';}
  function sw(tag){return `<span class="sw" style="background:${hexByTag[tag]||'#ddd'}"></span>`;}
  function iframe(){return $('#legacy-frame');}
  function frameDoc(){try{return iframe().contentDocument||iframe().contentWindow.document;}catch{return null;}}
  function frameReady(){const d=frameDoc();return !!(d&&d.querySelector('#btnProcess'));}

  function injectEngineSkin(){const d=frameDoc();if(!d||d.getElementById('pbn-studio-engine-skin'))return;const st=d.createElement('style');st.id='pbn-studio-engine-skin';st.textContent=`body{background:#fff!important}.container{width:96%!important;max-width:none!important}h2{display:none!important}#recolor-version-label{display:none!important}.row:first-child>span{font-size:12px;color:#687386}.tabs{box-shadow:none!important}.btn{border-radius:8px!important}.collection{border-radius:12px;overflow:hidden}.collection-item{border-color:#edf0f4!important}`;d.head.appendChild(st);}
  iframe().addEventListener('load',()=>{setTimeout(injectEngineSkin,700);$('#engine-status').textContent='Motor listo';});

  function collectSettings(d){const ids=['txtResizeWidth','txtResizeHeight','txtNrOfClusters','txtClusterPrecision','txtRandomSeed','txtNarrowPixelStripCleanupRuns','txtRemoveFacetsSmallerThan','txtMaximumNumberOfFacets','txtNrOfTimesToHalveBorderSegments','txtSizeMultiplier','txtLabelFontSize','txtLabelFontColor','txtKMeansColorRestrictions'];const o={};for(const id of ids){const el=d.getElementById(id);if(el)o[id]=el.value;}o.chkResizeImage=!!d.getElementById('chkResizeImage')?.checked;o.chkShowLabels=!!d.getElementById('chkShowLabels')?.checked;o.chkFillFacets=!!d.getElementById('chkFillFacets')?.checked;o.chkShowBorders=!!d.getElementById('chkShowBorders')?.checked;return o;}
  function analyzeSvg(svg){const counts=new Map();for(const el of svg.querySelectorAll('path,rect,circle,polygon,ellipse')){const vals=[el.getAttribute('fill'),el.style.fill,el.getAttribute('stroke'),el.style.stroke];for(const raw of vals){const h=cssHex(raw);if(!h||!tagByHex[h])continue;const tag=tagByHex[h];counts.set(tag,(counts.get(tag)||0)+1);break;}}return [...counts.entries()].map(([tag,weight])=>({tag,hex:hexByTag[tag],weight})).sort((a,b)=>b.weight-a.weight);}
  function deriveLineSvg(svgText){const doc=new DOMParser().parseFromString(svgText,'image/svg+xml'),svg=doc.documentElement;for(const el of svg.querySelectorAll('path,rect,circle,polygon,ellipse')){el.style.fill='white';el.setAttribute('fill','white');el.style.stroke='#b8bcc5';el.setAttribute('stroke','#b8bcc5');}return new XMLSerializer().serializeToString(svg);}
  function sourcePreview(d){try{const c=d.querySelector('#canvas');return c&&c.width&&c.height?c.toDataURL('image/png'):'';}catch{return '';}}
  function ensureProject(name){let p=activeProjectId&&S.get(activeProjectId);if(!p){p=S.upsert({id:S.uid('design'),name:name||'Nuevo diseño',status:'draft',versions:[]});activeProjectId=p.id;S.setActive(p.id);}else if(name&&p.name!==name){p=S.upsert({...p,name});}return p;}

  function captureCurrent(){const d=frameDoc();if(!d)return toast('El motor todavía no está listo.');const svg=d.querySelector('#svgContainer svg');if(!svg)return toast('Primero procesa la imagen y genera el Output/SVG en el motor.');const name=$('#design-name').value.trim()||'Nuevo diseño',p=ensureProject(name);const svgText=new XMLSerializer().serializeToString(svg),markers=analyzeSvg(svg);const version=S.addVersion(p.id,{name:`Captura ${p.versions.length+1}`,status:'draft',source:'generator2-legacy-engine',sourcePreview:sourcePreview(d),coloredSvg:svgText,lineSvg:deriveLineSvg(svgText),markers,markerTags:markers.map(x=>x.tag),settings:collectSettings(d),notes:'Capturada desde Generator 2'});activeVersionId=version.id;renderAll();openVersion(p.id,version.id);toast(`Guardado: ${p.name} · ${version.name}`);}

  function renderProjects(){const projects=S.list();$('#library-count').textContent=`${projects.length} diseño${projects.length===1?'':'s'}`;$('#project-grid').innerHTML=projects.length?projects.map(p=>{const v=p.versions[p.versions.length-1];const thumb=v?.coloredSvg?`<div class="thumb">${v.coloredSvg}</div>`:(v?.sourcePreview?`<img class="thumb-img" src="${v.sourcePreview}">`:'<div class="thumb empty">Sin preview</div>');return `<article class="project-card ${p.id===activeProjectId?'active':''}" data-project="${esc(p.id)}">${thumb}<div class="project-info"><div><h3>${esc(p.name)}</h3><small>${p.versions.length} versión${p.versions.length===1?'':'es'} · ${esc(p.status||'draft')}</small></div><button class="icon danger" data-delete="${esc(p.id)}" title="Eliminar">×</button></div></article>`;}).join(''):'<div class="empty-state">Todavía no guardaste diseños desde Generator 2.</div>';
    $$('.project-card').forEach(c=>c.addEventListener('click',e=>{if(e.target.closest('[data-delete]'))return;activeProjectId=c.dataset.project;S.setActive(activeProjectId);renderAll();const p=S.get(activeProjectId);if(p?.versions.length)openVersion(p.id,p.versions[p.versions.length-1].id);switchTab('library');}));
    $$('[data-delete]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();if(confirm('¿Eliminar este diseño y todas sus versiones locales?')){S.removeProject(b.dataset.delete);if(activeProjectId===b.dataset.delete){activeProjectId='';activeVersionId='';}renderAll();}}));
  }

  function renderActive(){const p=activeProjectId&&S.get(activeProjectId);$('#active-project-label').textContent=p?`${p.name} · ${p.versions.length} versiones`:'Sin proyecto activo';if(p&&!$('#design-name').matches(':focus'))$('#design-name').value=p.name;$('#version-list').innerHTML=p?.versions.length?p.versions.slice().reverse().map(v=>`<button class="version-row ${v.id===activeVersionId?'active':''}" data-version="${v.id}"><span>${esc(v.name)}</span><small>${esc(v.status)} · ${v.markerTags?.length||0} marcadores</small></button>`).join(''):'<div class="empty-state compact">Capturá una salida del motor para crear la primera versión.</div>';
    $$('.version-row').forEach(b=>b.addEventListener('click',()=>openVersion(p.id,b.dataset.version)));
  }

  function openVersion(projectId,versionId){const p=S.get(projectId),v=p?.versions.find(x=>x.id===versionId);if(!v)return;activeProjectId=projectId;activeVersionId=versionId;S.setActive(projectId);currentPreviewSvg=v.coloredSvg||'';$('#preview-title').textContent=`${p.name} · ${v.name}`;$('#preview-stage').innerHTML=currentPreviewSvg||'<div class="empty-state">Sin SVG</div>';$('#preview-meta').innerHTML=`<span>${v.markerTags?.length||0} marcadores</span><span>${esc(v.status)}</span><span>${new Date(v.createdAt).toLocaleString('es-CL')}</span>`;renderMarkerEditor(v);renderActive();}

  function renderMarkerEditor(v){const tags=v.markerTags||[];$('#marker-editor').innerHTML=tags.length?tags.map(tag=>`<div class="map-row"><span class="from-tag">${sw(tag)}<b>${esc(tag)}</b></span><span>→</span><select data-from="${esc(tag)}"><option value="${esc(tag)}">${esc(tag)} · mantener</option>${palette.filter(p=>String(p.tag)!==String(tag)).map(p=>`<option value="${esc(p.tag)}">${esc(p.tag)}</option>`).join('')}</select></div>`).join(''):'<div class="empty-state compact">No detecté marcadores exactos. Asegurate de haber aplicado la paleta de marcadores en Recolor antes de capturar.</div>';}

  function applySubstitutions(){const p=S.get(activeProjectId),v=p?.versions.find(x=>x.id===activeVersionId);if(!v?.coloredSvg)return;const subs={};for(const s of $$('#marker-editor select'))if(s.value!==s.dataset.from)subs[s.dataset.from]=s.value;const doc=new DOMParser().parseFromString(v.coloredSvg,'image/svg+xml'),svg=doc.documentElement;for(const el of svg.querySelectorAll('*')){for(const attr of ['fill','stroke']){const raw=el.getAttribute(attr)||el.style?.[attr],h=cssHex(raw),tag=tagByHex[h];if(tag&&subs[tag]){const nh=hexByTag[subs[tag]];el.setAttribute(attr,nh);if(el.style)el.style[attr]=nh;}}if(el.children.length===0){const t=(el.textContent||'').trim();if(subs[t])el.textContent=subs[t];}}
    currentPreviewSvg=new XMLSerializer().serializeToString(svg);$('#preview-stage').innerHTML=currentPreviewSvg;const n=Object.keys(subs).length;$('#preview-change-note').textContent=n?`${n} cambio${n===1?'':'s'} en preview: ${Object.entries(subs).map(([a,b])=>a+'→'+b).join(', ')}`:'Sin cambios';}

  function saveAsVersion(status='draft'){const p=S.get(activeProjectId),base=p?.versions.find(x=>x.id===activeVersionId);if(!p||!base||!currentPreviewSvg)return toast('No hay preview activa.');const markers=analyzeSvg(new DOMParser().parseFromString(currentPreviewSvg,'image/svg+xml').documentElement),v=S.addVersion(p.id,{name:`${status==='approved'?'Aprobada':'Optimizada'} ${p.versions.length+1}`,status,source:'generator2-preview',sourceVersionId:base.id,sourcePreview:base.sourcePreview,coloredSvg:currentPreviewSvg,lineSvg:deriveLineSvg(currentPreviewSvg),markers,markerTags:markers.map(x=>x.tag),settings:base.settings,notes:'Versión derivada desde editor de marcadores'});activeVersionId=v.id;renderAll();openVersion(p.id,v.id);toast(status==='approved'?'Versión aprobada y guardada.':'Nueva versión guardada.');}

  function selected(){const p=S.get(activeProjectId);return {p,v:p?.versions.find(x=>x.id===activeVersionId)};}
  function exportSvg(kind){const {p,v}=selected();if(!p||!v)return;const text=kind==='line'?(v.lineSvg||deriveLineSvg(v.coloredSvg)):v.coloredSvg;dl(`${slug(p.name)}-${slug(v.name)}-${kind}.svg`,text,'image/svg+xml');}
  function svgToPng(svgText,name){const svgBlob=new Blob([svgText],{type:'image/svg+xml'}),url=URL.createObjectURL(svgBlob),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth||img.width;c.height=img.naturalHeight||img.height;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0);URL.revokeObjectURL(url);c.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2500);},'image/png');};img.src=url;}
  function exportBundle(){const {p,v}=selected();if(!p||!v)return;dl(`${slug(p.name)}-${slug(v.name)}-project.json`,JSON.stringify({schema:1,project:{id:p.id,name:p.name},version:v},null,2),'application/json');}

  function renderProduction(){const approved=S.list().flatMap(p=>p.versions.filter(v=>v.status==='approved'||v.status==='applied').map(v=>({p,v})));$('#production-list').innerHTML=approved.length?approved.map(({p,v})=>`<article class="production-row"><div><b>${esc(p.name)}</b><small>${esc(v.name)} · ${v.markerTags?.length||0} marcadores</small></div><button data-open-prod="${p.id}|${v.id}">Abrir</button></article>`).join(''):'<div class="empty-state">No hay versiones aprobadas todavía.</div>';$$('[data-open-prod]').forEach(b=>b.addEventListener('click',()=>{const [p,v]=b.dataset.openProd.split('|');openVersion(p,v);switchTab('preview');}));}

  function renderAll(){renderProjects();renderActive();renderProduction();}
  function switchTab(name){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.view').forEach(v=>v.hidden=v.id!==`view-${name}`);}
  $$('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
  $('#capture').addEventListener('click',captureCurrent);$('#apply-preview').addEventListener('click',applySubstitutions);$('#save-version').addEventListener('click',()=>saveAsVersion('draft'));$('#approve-version').addEventListener('click',()=>saveAsVersion('approved'));
  $('#download-color-svg').addEventListener('click',()=>exportSvg('color'));$('#download-line-svg').addEventListener('click',()=>exportSvg('line'));$('#download-color-png').addEventListener('click',()=>{const {p,v}=selected();if(p&&v)svgToPng(v.coloredSvg,`${slug(p.name)}-${slug(v.name)}-color.png`);});$('#download-line-png').addEventListener('click',()=>{const {p,v}=selected();if(p&&v)svgToPng(v.lineSvg||deriveLineSvg(v.coloredSvg),`${slug(p.name)}-${slug(v.name)}-line.png`);});$('#download-bundle').addEventListener('click',exportBundle);
  $('#export-library').addEventListener('click',()=>dl('pbn-studio-library.json',JSON.stringify(S.exportAll(),null,2),'application/json'));$('#import-library').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{S.importAll(JSON.parse(await f.text()),true);renderAll();toast('Biblioteca importada.');}catch(err){alert(err.message);}e.target.value='';});
  $('#new-project').addEventListener('click',()=>{activeProjectId='';activeVersionId='';S.setActive('');$('#design-name').value='';renderAll();switchTab('create');});
  renderAll();switchTab('create');
})();
