(function(){
'use strict';
const C=window.PBNCloud,S=window.PBNStudioStorage,palette=window.PALETTE_ITEMS||[];
const $=s=>document.querySelector(s),tagSet=new Set(palette.map(p=>String(p.tag))),hexBy=Object.fromEntries(palette.map(p=>[String(p.tag),String(p.hex).toLowerCase()]));
const normName=s=>String(s||'').replace(/\.pdf$/i,'').replace(/paint by number generator/ig,'').replace(/paint by number/ig,'').replace(/paleta/ig,'').replace(/referencia/ig,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim();
const setKey=a=>[...new Set((a||[]).map(String))].sort((x,y)=>x.localeCompare(y,undefined,{numeric:true})).join('|');
const isDirectImageUrl=u=>{try{const x=new URL(String(u||''));return /res\.cloudinary\.com$/i.test(x.hostname)||/\.(?:png|jpe?g|webp|gif|avif)$/i.test(x.pathname);}catch{return false;}};
function msg(t,kind=''){let el=$('#legacy-import-status');if(!el){el=document.createElement('div');el.id='legacy-import-status';el.className='cloud-banner';const panel=$('#project-grid')?.parentElement;panel?.insertBefore(el,$('#project-grid'));}el.className=`cloud-banner ${kind}`;el.textContent=t;}
async function readPdf(file){if(!window.pdfjsLib)throw new Error('PDF.js no cargó');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const buf=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data:buf}).promise,page=await pdf.getPage(1),tc=await page.getTextContent();const items=tc.items.map(x=>String(x.str||'').trim()).filter(Boolean),joined=items.join(' ');let markerText=joined;const mi=joined.toLowerCase().indexOf('marcadores incluidos');if(mi>=0)markerText=joined.slice(mi);const tip=markerText.toLowerCase().indexOf('tip:');if(tip>=0)markerText=markerText.slice(0,tip);const tokens=markerText.match(/[A-Za-z]+\d+(?:\.\d+)?|\d+(?:\.\d+)?/g)||[],markers=[];for(const t of tokens){if(tagSet.has(t)&&!markers.includes(t))markers.push(t);}const viewport=page.getViewport({scale:3}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext('2d',{willReadFrequently:true});await page.render({canvasContext:ctx,viewport}).promise;let qr='';if(window.jsQR){const img=ctx.getImageData(0,0,canvas.width,canvas.height),code=jsQR(img.data,img.width,img.height,{inversionAttempts:'attemptBoth'});qr=code?.data||'';}return{markers,qr,text:joined};}
async function upsertAsset(versionId,kind,{path=null,url=null,mime=null,meta={}}={}){const {error}=await C.client.from('pbn_assets').upsert({version_id:versionId,kind,storage_path:path,external_url:url,mime_type:mime,metadata:meta},{onConflict:'version_id,kind'});if(error)throw error;}
async function uploadPdf(designId,versionId,file){const path=`designs/${designId}/versions/${versionId}/legacy.pdf`,{data,error}=await C.client.storage.from(C.BUCKET).upload(path,file,{upsert:true,contentType:'application/pdf'});if(error)throw error;await upsertAsset(versionId,'pdf',{path:data.path,mime:'application/pdf',meta:{legacy:true,filename:file.name}});return data.path;}
async function saveReference(designId,versionId,qr,metadata={}){if(!qr)return;const direct=isDirectImageUrl(qr),kind=direct?'cloudinary_reference':'reference_link';await upsertAsset(versionId,kind,{url:qr,mime:direct?'image/png':'text/uri-list',meta:{source:'pdf_qr',...metadata}});const patch={metadata:{...metadata,reference_qr_url:qr,reference_qr_direct_image:direct}};if(direct)patch.legacy_cloudinary_url=qr;else patch.legacy_cloudinary_url=null;const {error}=await C.client.from('pbn_designs').update(patch).eq('id',designId);if(error)throw error;}
async function createLegacy(file,markers,qr){const name=normName(file.name)||`Importado ${Date.now()}`,slug=C.slug(name),direct=isDirectImageUrl(qr);const {data:d,error:de}=await C.client.from('pbn_designs').upsert({name,slug,status:'active',source_type:'legacy_pdf',legacy_cloudinary_url:direct?qr:null,metadata:{legacy_filename:file.name,imported_from:'generator2',reference_qr_url:qr||null,reference_qr_direct_image:direct}},{onConflict:'slug'}).select().single();if(de)throw de;const {data:v,error:ve}=await C.client.from('pbn_design_versions').upsert({design_id:d.id,version_name:'Actual',status:'approved',generator_version:'legacy',is_structured:false,settings:{source_file:file.name},notes:'Importado automáticamente desde PDF antiguo'},{onConflict:'design_id,version_name'}).select().single();if(ve)throw ve;const rows=markers.map((tag,i)=>({version_id:v.id,marker_tag:tag,palette_hex:hexBy[tag]||'#000000',sort_order:i,area_weight:1,frequency:0,metadata:{source:'legacy_pdf'}}));await C.client.from('pbn_version_markers').delete().eq('version_id',v.id);if(rows.length){const {error}=await C.client.from('pbn_version_markers').insert(rows);if(error)throw error;}await uploadPdf(d.id,v.id,file);if(qr)await saveReference(d.id,v.id,qr,{legacy_filename:file.name,imported_from:'generator2'});return{name,designId:d.id,versionId:v.id,matched:false,direct};}
async function attachToMatch(match,file,markers,qr){const dId=match.project.cloudId,vId=match.version.cloudId;await uploadPdf(dId,vId,file);if(qr)await saveReference(dId,vId,qr,{...(match.project.metadata||{}),legacy_filename:file.name,legacy_qr_verified:true});return{name:match.project.name,designId:dId,versionId:vId,matched:true,direct:isDirectImageUrl(qr)};}
function findMatch(projects,file,markers){const key=setKey(markers),hits=[];for(const p of projects)for(const v of p.versions||[])if(setKey(v.markerTags)===key)hits.push({project:p,version:v});if(hits.length<=1)return hits[0]||null;const fn=normName(file.name).toLowerCase();return hits.sort((a,b)=>{const as=String(a.version.settings?.source_file||a.project.name).toLowerCase(),bs=String(b.version.settings?.source_file||b.project.name).toLowerCase();return (bs.includes(fn)?1:0)-(as.includes(fn)?1:0);})[0];}
async function importFiles(files){if(!C.session())throw new Error('Inicia sesión antes de importar PDFs antiguos.');let projects=await C.loadProjects(),ok=0,created=0,failed=0;for(let i=0;i<files.length;i++){const file=files[i];msg(`Leyendo ${i+1}/${files.length}: ${file.name}…`,'syncing');try{const info=await readPdf(file);if(!info.markers.length)throw new Error('No pude detectar una receta de marcadores en la primera página.');const match=findMatch(projects,file,info.markers);const r=match?await attachToMatch(match,file,info.markers,info.qr):await createLegacy(file,info.markers,info.qr);ok++;if(!r.matched)created++;msg(`✓ ${file.name}: ${r.matched?'vinculado a '+r.name:'creado como '+r.name}${info.qr?(r.direct?' · imagen QR detectada':' · QR detectado; preview se recupera desde el PDF'):' · sin QR detectado'}`,'ok');projects=await C.loadProjects();}catch(e){failed++;console.error(file.name,e);msg(`Error en ${file.name}: ${e.message}`,'error');}}
msg(`Importación terminada: ${ok} PDF(s) procesados · ${created} diseño(s) nuevos · ${failed} error(es). Recargando biblioteca…`,failed?'error':'ok');setTimeout(()=>location.reload(),1000);}
const input=$('#legacy-pdf-import');if(input)input.addEventListener('change',async e=>{const files=[...(e.target.files||[])];e.target.value='';if(!files.length)return;try{await importFiles(files);}catch(err){msg(err.message,'error');}});
})();