(function(){
'use strict';
const S=window.PBNStudioStorage,C=window.PBNCloud,palette=window.PALETTE_ITEMS||[],$=s=>document.querySelector(s);
const hexBy=Object.fromEntries(palette.map(p=>[String(p.tag),String(p.hex)]));
const slug=s=>String(s||'design').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'design';
function toast(t){let n=document.createElement('div');n.className='toast';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),4500);}
function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob);});}
async function svgToPng(svgText,maxSide=5000){const blob=new Blob([svgText],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url;});const vb=(svgText.match(/viewBox=["']([^"']+)/i)?.[1]||'').trim().split(/\s+/).map(Number),baseW=(vb.length===4&&vb[2])||img.naturalWidth||1600,baseH=(vb.length===4&&vb[3])||img.naturalHeight||1600,scale=Math.min(4,maxSide/Math.max(baseW,baseH)),w=Math.max(1,Math.round(baseW*scale)),h=Math.max(1,Math.round(baseH*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,w,h);URL.revokeObjectURL(url);const png=await new Promise(r=>c.toBlob(r,'image/png',1));return{blob:png,dataUrl:c.toDataURL('image/png'),width:w,height:h};}
async function uploadCloudinary(blob,name){const form=new FormData();form.append('file',blob,`${slug(name)}.png`);form.append('upload_preset','pbn_unsigned');form.append('folder','paintbynumber-referencias');form.append('public_id',`${slug(name)}-${Date.now()}`);const r=await fetch('https://api.cloudinary.com/v1_1/df4fayh1q/image/upload',{method:'POST',body:form}),j=await r.json();if(!r.ok||!j.secure_url)throw new Error(j.error?.message||'Falló Cloudinary');return j.secure_url;}
async function fetchAsDataUrl(url){const r=await fetch(url);if(!r.ok)throw new Error('No pude cargar plantilla');return blobToDataURL(await r.blob());}
function fit(sw,sh,bw,bh){const s=Math.min(bw/sw,bh/sh);return{w:sw*s,h:sh*s};}
async function makePdf(project,version,colorPng,publicUrl){if(!window.jspdf?.jsPDF)throw new Error('jsPDF no cargó');const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'mm',format:[216,330],compress:true}),bgUrl=new URL('../assets/clean_template_v3.png',location.href).href,bg=await fetchAsDataUrl(bgUrl);pdf.addImage(bg,'PNG',7,7,202,316,undefined,'FAST');if(publicUrl&&window.QRCode?.toDataURL){const qr=await QRCode.toDataURL(publicUrl,{width:420,margin:1,errorCorrectionLevel:'M'});pdf.addImage(qr,'PNG',173.3,12,23,23,undefined,'FAST');}
const dim=fit(colorPng.width,colorPng.height,171,160),x=108-dim.w/2,y=73.8+(160-dim.h)/2;pdf.addImage(colorPng.dataUrl,'PNG',x,y,dim.w,dim.h,undefined,'FAST');const tags=version.markerTags||version.markers?.map(m=>m.tag)||[];pdf.setFont('helvetica','bold');pdf.setTextColor(44,44,44);pdf.setFontSize(11);pdf.text(`Marcadores incluidos (${tags.length} colores)`,20,244);let cx=20,cy=249;for(const tag of tags){const hex=hexBy[tag]||'#dddddd',rgb=hex.replace('#','').match(/.{2}/g).map(x=>parseInt(x,16));let w=Math.max(12,6+String(tag).length*2.2);if(cx+w>196){cx=20;cy+=10;}pdf.setFillColor(...rgb);pdf.roundedRect(cx,cy,w,7,1.4,1.4,'F');const lum=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];pdf.setTextColor(lum<130?255:20,lum<130?255:20,lum<130?255:20);pdf.setFontSize(8);pdf.text(String(tag),cx+w/2,cy+4.8,{align:'center'});cx+=w+3;}pdf.setProperties({title:`Paint by number generator ${project.name}`,subject:`${version.name} · ${tags.length} marcadores`});return pdf.output('blob');}
async function uploadSupabaseAsset(project,version,kind,blob,filename,mime){if(!C?.session()||!project.cloudId||!version.cloudId)return;const path=`designs/${project.cloudId}/versions/${version.cloudId}/${filename}`,{data,error}=await C.client.storage.from(C.BUCKET).upload(path,blob,{upsert:true,contentType:mime});if(error)throw error;const {error:ae}=await C.client.from('pbn_assets').upsert({version_id:version.cloudId,kind,storage_path:data.path,mime_type:mime,bytes:blob.size,metadata:{generated_by:'generator2-production'}},{onConflict:'version_id,kind'});if(ae)throw ae;}
async function externalRef(version,url){if(!C?.session()||!version.cloudId||!url)return;const {error}=await C.client.from('pbn_assets').upsert({version_id:version.cloudId,kind:'cloudinary_reference',external_url:url,mime_type:'image/png',metadata:{generated_by:'generator2-production'}},{onConflict:'version_id,kind'});if(error)throw error;}
async function buildPackage(projectId,versionId,button){let p=S.get(projectId),v=p?.versions.find(x=>x.id===versionId);if(!p||!v)throw new Error('Versión no encontrada');if(!v.coloredSvg)throw new Error('Esta versión es legacy y todavía no tiene SVG estructurado. Regenerala en Generator 2 antes de producir archivos nuevos.');button.disabled=true;button.textContent='Generando…';try{if(C?.session()){const synced=await C.syncProject(p);S.upsert(synced);p=S.get(projectId)||synced;v=p.versions.find(x=>x.id===versionId)||p.versions.find(x=>x.name===v.name)||v;}toast('Rasterizando SVG color y líneas…');const color=await svgToPng(v.coloredSvg),lineSvg=v.lineSvg||v.coloredSvg,line=await svgToPng(lineSvg);toast('Subiendo referencia pública para el QR…');const publicUrl=await uploadCloudinary(color.blob,`${p.name}-${v.name}`);const pdfBlob=await makePdf(p,v,color,publicUrl),recipe={schema:1,design:p.name,version:v.name,markers:v.markerTags||[],publicReference:publicUrl,generatedAt:new Date().toISOString()};if(C?.session()){await externalRef(v,publicUrl);await Promise.all([uploadSupabaseAsset(p,v,'png_color',color.blob,'color.png','image/png'),uploadSupabaseAsset(p,v,'png_line',line.blob,'line.png','image/png'),uploadSupabaseAsset(p,v,'pdf',pdfBlob,'print.pdf','application/pdf')]);}
const zip=new JSZip(),base=`${slug(p.name)}-${slug(v.name)}`;zip.file(`${base}-color.svg`,v.coloredSvg);zip.file(`${base}-line.svg`,lineSvg);zip.file(`${base}-color.png`,color.blob);zip.file(`${base}-line.png`,line.blob);zip.file(`${base}-print.pdf`,pdfBlob);zip.file(`${base}-recipe.json`,JSON.stringify(recipe,null,2));const out=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),a=document.createElement('a');a.href=URL.createObjectURL(out);a.download=`${base}-PAQUETE-PRODUCCION.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4000);toast('✓ Paquete de producción listo: SVG + PNG + PDF + receta.');}finally{button.disabled=false;button.textContent='Paquete final';}}
function enhance(){document.querySelectorAll('.production-row').forEach(row=>{if(row.querySelector('[data-package]'))return;const open=row.querySelector('[data-open-prod]');if(!open)return;const [pId,vId]=open.dataset.openProd.split('|'),p=S.get(pId),v=p?.versions.find(x=>x.id===vId),b=document.createElement('button');b.dataset.package='1';b.textContent=v?.coloredSvg?'Paquete final':'Legacy · falta SVG';b.disabled=!v?.coloredSvg;b.title=v?.coloredSvg?'Regenera y descarga ZIP con SVG, PNG, PDF y receta':'Esta versión sólo tiene receta/preview raster';b.addEventListener('click',()=>buildPackage(pId,vId,b).catch(e=>{console.error(e);alert(e.message);}));row.appendChild(b);});}
const target=$('#production-list');if(target){new MutationObserver(enhance).observe(target,{childList:true,subtree:true});enhance();}
})();