(function(){
'use strict';
const C=window.PBNCloud,S=window.PBNStudioStorage,palette=window.PALETTE_ITEMS||[],$=s=>document.querySelector(s);
const hexBy=Object.fromEntries(palette.map(p=>[String(p.tag),String(p.hex)]));
let selectedRun=null,byVersion=new Map(),loading=false;
const requestedRun=new URLSearchParams(location.search).get('run');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function sw(tag){return `<span style="display:inline-block;width:14px;height:14px;border-radius:4px;border:1px solid rgba(0,0,0,.18);background:${hexBy[String(tag)]||'#ddd'};vertical-align:-2px;margin-right:4px"></span>`;}
async function chooseRun(){if(requestedRun){const {data,error}=await C.client.from('pbn_optimization_runs').select('id,created_at,status,summary,settings').eq('id',requestedRun).maybeSingle();if(error)throw error;return data||null;}const {data,error}=await C.client.from('pbn_optimization_runs').select('id,created_at,status,summary,settings').eq('mode','optimizer2_global').eq('status','completed').order('created_at',{ascending:false}).limit(20);if(error)throw error;return (data||[]).find(r=>!r.summary?.stale)||null;}
async function load(){if(!C?.admin()||loading)return;loading=true;try{selectedRun=await chooseRun();byVersion=new Map();if(selectedRun){const {data:changes,error:ce}=await C.client.from('pbn_optimization_changes').select('*').eq('optimization_run_id',selectedRun.id);if(ce)throw ce;for(const c of changes||[]){if(!byVersion.has(c.base_version_id))byVersion.set(c.base_version_id,[]);byVersion.get(c.base_version_id).push(c);}}paint();}catch(e){console.warn('proposal load',e);}finally{loading=false;}}
function activeVersion(){const p=S.get(S.getActive()),id=$('.version-row.active')?.dataset.version,v=p?.versions?.find(x=>x.id===id);return{p,v};}
function ensureHost(){let host=$('#optimizer-proposals');if(host)return host;const panel=$('.editor-panel');if(!panel)return null;host=document.createElement('div');host.id='optimizer-proposals';host.style.cssText='margin:14px 0;padding:12px;border:1px solid #ded9ff;border-radius:12px;background:#faf9ff';const hr=panel.querySelector('hr');panel.insertBefore(host,hr||panel.firstChild);return host;}
function paint(){const host=ensureHost();if(!host)return;const {p,v}=activeVersion();if(!C?.admin()){host.innerHTML='<b>Propuestas de Plan Maestro</b><p class="muted">Activa la nube para ver propuestas guardadas.</p>';return;}if(!p||!v){host.innerHTML='<b>Propuestas de Plan Maestro</b><p class="muted">Abrí una versión para consultar sus cambios.</p>';return;}if(!selectedRun){host.innerHTML='<b>Propuestas de Plan Maestro</b><p class="muted">No hay un Plan Maestro vigente posterior a la corrección de recetas. Generá uno nuevo en el Paso 03.</p>';return;}const changes=byVersion.get(v.cloudId)||[],stale=!!selectedRun.summary?.stale;if(!changes.length){host.innerHTML=`<b>${requestedRun?'Plan seleccionado':'Plan Maestro vigente'}</b><p class="muted">${new Date(selectedRun.created_at).toLocaleString('es-CL')} · esta receta no necesitó cambios.${stale?' ⚠ Este plan es histórico y fue generado antes de una corrección de recetas.':''}</p>`;return;}host.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div><b>Propuesta de Plan Maestro${stale?' · HISTÓRICA':''}</b><small style="display:block;color:${stale?'#a16207':'#6b7280'}">${new Date(selectedRun.created_at).toLocaleString('es-CL')} · ${changes.length} cambio${changes.length===1?'':'s'}${stale?' · recetas base corregidas después':''}</small></div><button id="apply-optimizer-proposal" class="primary" ${stale?'title="Podés verla, pero conviene generar un Plan Maestro nuevo"':''}>Cargar a preview</button></div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:10px">${changes.sort((a,b)=>Number(a.delta_e||0)-Number(b.delta_e||0)).map(c=>`<span style="display:inline-flex;align-items:center;gap:4px;padding:6px 8px;border-radius:9px;background:${c.strategic_move?'#eee9ff':'#fff1dd'};border:1px solid ${c.strategic_move?'#c8b9ff':'#f1c77f'}">${sw(c.from_marker)}<b>${esc(c.from_marker)}</b><span>→</span>${sw(c.to_marker)}<b>${esc(c.to_marker)}</b><span>· ΔE ${Number(c.delta_e||0).toFixed(2).replace('.',',')}</span></span>`).join('')}</div>`;$('#apply-optimizer-proposal').onclick=()=>apply(changes);}
function apply(changes){const {v}=activeVersion();if(!v)return;let n=0;for(const c of changes){const sel=document.querySelector(`#marker-editor select[data-from="${CSS.escape(String(c.from_marker))}"]`);if(sel&&[...sel.options].some(o=>o.value===String(c.to_marker))){sel.value=String(c.to_marker);sel.dispatchEvent(new Event('change',{bubbles:true}));n++;}}if(n){$('#apply-preview')?.click();const note=$('#preview-change-note');if(note)note.textContent+=` · propuesta del Plan Maestro cargada (${n} cambios)`;}else alert('No pude mapear esos cambios en la receta actual. Puede ser una versión distinta a la base de este Plan Maestro.');}
C?.onSession((s,isAdmin)=>{if(s&&isAdmin)load();else paint();});document.addEventListener('click',e=>{if(e.target.closest?.('.version-row'))setTimeout(paint,50);});const vl=$('#version-list');if(vl)new MutationObserver(()=>setTimeout(paint,30)).observe(vl,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});setTimeout(paint,350);
})();