(function(){
'use strict';
const C=window.PBNCloud,S=window.PBNStudioStorage,$=s=>document.querySelector(s);
let latestRun=null,byVersion=new Map(),loading=false;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
async function load(){if(!C?.admin()||loading)return;loading=true;try{const {data:runs,error:re}=await C.client.from('pbn_optimization_runs').select('id,created_at,status,summary,settings').eq('status','completed').order('created_at',{ascending:false}).limit(1);if(re)throw re;latestRun=runs?.[0]||null;byVersion=new Map();if(latestRun){const {data:changes,error:ce}=await C.client.from('pbn_optimization_changes').select('*').eq('optimization_run_id',latestRun.id);if(ce)throw ce;for(const c of changes||[]){if(!byVersion.has(c.base_version_id))byVersion.set(c.base_version_id,[]);byVersion.get(c.base_version_id).push(c);}}paint();}catch(e){console.warn('proposal load',e);}finally{loading=false;}}
function activeVersion(){const p=S.get(S.getActive()),id=$('.version-row.active')?.dataset.version,v=p?.versions?.find(x=>x.id===id);return{p,v};}
function ensureHost(){let host=$('#optimizer-proposals');if(host)return host;const panel=$('.editor-panel');if(!panel)return null;host=document.createElement('div');host.id='optimizer-proposals';host.style.cssText='margin:14px 0;padding:12px;border:1px solid #ded9ff;border-radius:12px;background:#faf9ff';const hr=panel.querySelector('hr');panel.insertBefore(host,hr||panel.firstChild);return host;}
function paint(){const host=ensureHost();if(!host)return;const {p,v}=activeVersion();if(!C?.admin()){host.innerHTML='<b>Propuestas de Optimizer 2</b><p class="muted">Activa la nube para ver propuestas guardadas.</p>';return;}if(!p||!v){host.innerHTML='<b>Propuestas de Optimizer 2</b><p class="muted">Abrí una versión para consultar sus cambios.</p>';return;}const changes=byVersion.get(v.cloudId)||[];if(!latestRun){host.innerHTML='<b>Propuestas de Optimizer 2</b><p class="muted">Todavía no hay corridas guardadas en Supabase.</p>';return;}if(!changes.length){host.innerHTML=`<b>Última corrida</b><p class="muted">${new Date(latestRun.created_at).toLocaleString('es-CL')} · esta receta no necesitó cambios en la última propuesta.</p>`;return;}host.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div><b>Propuesta de Optimizer 2</b><small style="display:block;color:#6b7280">${new Date(latestRun.created_at).toLocaleString('es-CL')} · ${changes.length} cambio${changes.length===1?'':'s'}</small></div><button id="apply-optimizer-proposal" class="primary">Cargar a preview</button></div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:10px">${changes.sort((a,b)=>Number(a.delta_e||0)-Number(b.delta_e||0)).map(c=>`<span style="padding:6px 8px;border-radius:9px;background:${c.strategic_move?'#eee9ff':'#fff1dd'};border:1px solid ${c.strategic_move?'#c8b9ff':'#f1c77f'}"><b>${esc(c.from_marker)}→${esc(c.to_marker)}</b> · ΔE ${Number(c.delta_e||0).toFixed(2).replace('.',',')}</span>`).join('')}</div>`;$('#apply-optimizer-proposal').onclick=()=>apply(changes);}
function apply(changes){const {v}=activeVersion();if(!v)return;let n=0;for(const c of changes){const sel=document.querySelector(`#marker-editor select[data-from="${CSS.escape(String(c.from_marker))}"]`);if(sel&&[...sel.options].some(o=>o.value===String(c.to_marker))){sel.value=String(c.to_marker);n++;}}if(n){$('#apply-preview')?.click();const note=$('#preview-change-note');if(note)note.textContent+=` · propuesta Optimizer 2 cargada (${n} cambios)`;}else alert('No pude mapear esos cambios en el editor actual. Esta receta puede ser legacy o distinta a la base de la propuesta.');}
C?.onSession((s,isAdmin)=>{if(s&&isAdmin)load();else paint();});
document.addEventListener('click',e=>{if(e.target.closest?.('.version-row'))setTimeout(paint,40);});const vl=$('#version-list');if(vl)new MutationObserver(()=>setTimeout(paint,20)).observe(vl,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});setTimeout(paint,300);
})();