(function(root){
'use strict';
const URL='https://mxjehmvrobpaetmhrgqz.supabase.co';
const KEY='sb_publishable_Wv-jIr91qZ4N5pYv6dVdHg_UZFQJHt4';
const BUCKET='pbn-studio-assets';
const client=root.supabase&&root.supabase.createClient?root.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
const listeners=new Set();
let currentSession=null,currentAdmin=false,adminChecked=false;
const slug=s=>String(s||'design').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'design';
const statusMap=s=>s==='approved'?'approved':s==='applied'?'applied':s==='validated'?'validated':'draft';
function emit(){listeners.forEach(fn=>{try{fn(currentSession,currentAdmin);}catch(e){console.warn(e);}});}
async function refreshAdmin(){adminChecked=false;currentAdmin=false;if(!client||!currentSession){adminChecked=true;emit();return false;}try{const {data,error}=await client.rpc('pbn_is_admin');if(error)throw error;currentAdmin=!!data;}catch(e){console.warn('PBN admin check',e);currentAdmin=false;}adminChecked=true;emit();return currentAdmin;}
async function init(){if(!client)return null;const {data}=await client.auth.getSession();currentSession=data.session||null;await refreshAdmin();client.auth.onAuthStateChange(async(_e,s)=>{currentSession=s||null;await refreshAdmin();});return currentSession;}
function onSession(fn){listeners.add(fn);try{fn(currentSession,currentAdmin);}catch(_){}return()=>listeners.delete(fn);}
function session(){return currentSession;}
function admin(){return currentAdmin;}
function requireAdmin(){if(!currentSession)throw new Error('Inicia sesión para usar Byte by Number.');if(!currentAdmin)throw new Error('Esta cuenta todavía no fue activada como administradora.');}
async function signUp(email,password){if(!client)throw new Error('Supabase SDK no cargado');const {data,error}=await client.auth.signUp({email,password});if(error)throw error;if(data.session){currentSession=data.session;await refreshAdmin();}return data;}
async function signIn(email,password){const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;currentSession=data.session||null;await refreshAdmin();return data;}
async function signOut(){if(!client)return;const {error}=await client.auth.signOut();if(error)throw error;currentSession=null;currentAdmin=false;adminChecked=true;emit();}
async function claimAdmin(code){if(!currentSession)throw new Error('Primero inicia sesión.');const {data,error}=await client.rpc('pbn_claim_admin',{p_code:String(code||'').trim()});if(error)throw error;if(!data)throw new Error('Código de activación incorrecto o ya utilizado por otra cuenta.');currentAdmin=true;adminChecked=true;emit();return true;}
function mountAuth(hostOrSelector){const host=typeof hostOrSelector==='string'?document.querySelector(hostOrSelector):hostOrSelector;if(!host)return;function paint(){const s=currentSession;if(s&&currentAdmin){host.innerHTML=`<div class="cloud-auth signed"><span class="cloud-dot"></span><div><b>Nube conectada</b><small>${escapeHtml(s.user?.email||'usuario')}</small></div><button data-cloud-out>Salir</button></div>`;host.querySelector('[data-cloud-out]')?.addEventListener('click',()=>signOut().catch(e=>alert(e.message)));return;}if(s&&!currentAdmin){host.innerHTML=`<div class="cloud-auth cloud-claim"><div><b>Activar administrador</b><small>${escapeHtml(s.user?.email||'cuenta autenticada')}</small></div><input data-cloud-code placeholder="Código inicial" autocomplete="one-time-code"><button data-cloud-claim>Activar</button><button data-cloud-out>Salir</button><small data-cloud-msg>Esta base está bloqueada hasta reclamar el administrador único.</small></div>`;const msg=t=>host.querySelector('[data-cloud-msg]').textContent=t;host.querySelector('[data-cloud-claim]').onclick=async()=>{try{msg('Activando…');await claimAdmin(host.querySelector('[data-cloud-code]').value);msg('Administrador activado.');}catch(e){msg(e.message);}};host.querySelector('[data-cloud-out]').onclick=()=>signOut().catch(e=>alert(e.message));return;}host.innerHTML=`<div class="cloud-auth"><div class="cloud-fields"><input data-cloud-email type="email" placeholder="Email"><input data-cloud-pass type="password" minlength="6" placeholder="Contraseña"></div><button data-cloud-in>Entrar</button><button data-cloud-up>Crear acceso</button><small data-cloud-msg>Inicia sesión. La primera cuenta debe activar el código de administrador.</small></div>`;const email=()=>host.querySelector('[data-cloud-email]').value.trim(),pass=()=>host.querySelector('[data-cloud-pass]').value;const msg=t=>host.querySelector('[data-cloud-msg]').textContent=t;host.querySelector('[data-cloud-in]').onclick=async()=>{try{msg('Entrando…');await signIn(email(),pass());}catch(e){msg(e.message);}};host.querySelector('[data-cloud-up]').onclick=async()=>{try{msg('Creando acceso…');const d=await signUp(email(),pass());msg(d.session?'Acceso creado. Ahora activa el código de administrador.':'Acceso creado. Si Supabase pide confirmar el correo, confírmalo y luego entra.');}catch(e){msg(e.message);}};}onSession(paint);paint();}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
async function seedPalette(items){requireAdmin();if(!Array.isArray(items)||!items.length)return;const {count,error:ce}=await client.from('pbn_palette_markers').select('*',{count:'exact',head:true});if(ce)throw ce;if((count||0)>=items.length)return;const rows=items.map(x=>({marker_tag:String(x.tag),palette_hex:String(x.hex).toLowerCase(),active:true}));const {error}=await client.from('pbn_palette_markers').upsert(rows,{onConflict:'marker_tag'});if(error)throw error;for(const x of rows){const {error:e}=await client.from('pbn_version_markers').update({palette_hex:x.palette_hex}).eq('marker_tag',x.marker_tag).eq('palette_hex','#000000');if(e)throw e;}}
async function uploadText(path,text,type){requireAdmin();const blob=new Blob([text],{type:type||'text/plain'});const {data,error}=await client.storage.from(BUCKET).upload(path,blob,{upsert:true,contentType:type||'text/plain'});if(error)throw error;return data.path;}
async function uploadDataUrl(path,dataUrl){requireAdmin();if(!dataUrl||!/^data:/.test(dataUrl))return null;const r=await fetch(dataUrl),blob=await r.blob();const {data,error}=await client.storage.from(BUCKET).upload(path,blob,{upsert:true,contentType:blob.type||'application/octet-stream'});if(error)throw error;return data.path;}
async function upsertAsset(versionId,kind,storagePath,mime,externalUrl,metadata){requireAdmin();if(!versionId||(!storagePath&&!externalUrl))return;const row={version_id:versionId,kind,storage_path:storagePath||null,external_url:externalUrl||null,mime_type:mime||null,metadata:metadata||{}};const {error}=await client.from('pbn_assets').upsert(row,{onConflict:'version_id,kind'});if(error)throw error;}
async function syncProject(project){requireAdmin();if(!project)throw new Error('Proyecto inválido');const s=slug(project.name),{data:design,error:de}=await client.from('pbn_designs').upsert({name:project.name,slug:s,status:project.status==='archived'?'archived':'active',source_type:'generator2',metadata:{local_id:project.id,synced_from:'generator2'}},{onConflict:'slug'}).select().single();if(de)throw de;const out={...project,cloudId:design.id};for(const version of project.versions||[]){const bundle={schema:1,localVersionId:version.id,coloredSvg:version.coloredSvg||'',lineSvg:version.lineSvg||'',markerTags:version.markerTags||[],markers:version.markers||[],settings:version.settings||{},notes:version.notes||''};const {data:v,error:ve}=await client.from('pbn_design_versions').upsert({design_id:design.id,version_name:version.name||'Actual',status:statusMap(version.status),generator_version:version.source||'generator2',is_structured:!!version.coloredSvg,settings:version.settings||{},project_bundle:bundle,notes:version.notes||null},{onConflict:'design_id,version_name'}).select().single();if(ve)throw ve;version.cloudId=v.id;const rows=(version.markers||[]).map((m,i)=>({version_id:v.id,marker_tag:String(m.tag),palette_hex:String(m.hex||'#000000').toLowerCase(),area_weight:Number(m.weight||m.area_weight||1),frequency:Number(m.frequency||m.weight||0),sort_order:i,metadata:{source:'generator2'}}));if(rows.length){const {error:del}=await client.from('pbn_version_markers').delete().eq('version_id',v.id);if(del)throw del;const {error:me}=await client.from('pbn_version_markers').insert(rows);if(me)throw me;}const base=`designs/${design.id}/versions/${v.id}`;if(version.coloredSvg){const p=await uploadText(`${base}/color.svg`,version.coloredSvg,'image/svg+xml');await upsertAsset(v.id,'svg_color',p,'image/svg+xml');}if(version.lineSvg){const p=await uploadText(`${base}/line.svg`,version.lineSvg,'image/svg+xml');await upsertAsset(v.id,'svg_line',p,'image/svg+xml');}if(version.sourcePreview&&/^data:/.test(version.sourcePreview)){const ext=version.sourcePreview.startsWith('data:image/jpeg')?'jpg':'png',mime=ext==='jpg'?'image/jpeg':'image/png';const p=await uploadDataUrl(`${base}/source.${ext}`,version.sourcePreview);await upsertAsset(v.id,'source',p,mime);}const jp=await uploadText(`${base}/project.json`,JSON.stringify({design:{id:design.id,name:project.name,slug:s},version:bundle},null,2),'application/json');await upsertAsset(v.id,'project_json',jp,'application/json');}
return out;}
async function deleteCloudProject(project){requireAdmin();if(!project)return;let id=project.cloudId;if(!id){const {data}=await client.from('pbn_designs').select('id').eq('slug',slug(project.name)).maybeSingle();id=data?.id;}if(id){const {error}=await client.from('pbn_designs').delete().eq('id',id);if(error)throw error;}}
async function loadProjects(){requireAdmin();const [{data:designs,error:de},{data:versions,error:ve},{data:markers,error:me},{data:assets,error:ae}]=await Promise.all([client.from('pbn_designs').select('*').order('name'),client.from('pbn_design_versions').select('*').order('created_at'),client.from('pbn_version_markers').select('*').order('sort_order'),client.from('pbn_assets').select('*')]);if(de)throw de;if(ve)throw ve;if(me)throw me;if(ae)throw ae;const markersBy=new Map(),assetsBy=new Map();(markers||[]).forEach(m=>{if(!markersBy.has(m.version_id))markersBy.set(m.version_id,[]);markersBy.get(m.version_id).push(m);});(assets||[]).forEach(a=>{if(!assetsBy.has(a.version_id))assetsBy.set(a.version_id,[]);assetsBy.get(a.version_id).push(a);});const versionsBy=new Map();(versions||[]).forEach(v=>{if(!versionsBy.has(v.design_id))versionsBy.set(v.design_id,[]);const ms=markersBy.get(v.id)||[],as=assetsBy.get(v.id)||[],cloudRef=as.find(a=>a.kind==='cloudinary_reference')?.external_url||'';const b=v.project_bundle||{};versionsBy.get(v.design_id).push({id:`cloud_${v.id}`,cloudId:v.id,name:v.version_name,status:v.status==='approved'?'approved':v.status,createdAt:v.created_at,updatedAt:v.updated_at,source:v.generator_version||'cloud',coloredSvg:b.coloredSvg||'',lineSvg:b.lineSvg||'',sourcePreview:cloudRef,previewUrl:cloudRef,markers:ms.map(m=>({tag:m.marker_tag,hex:m.palette_hex,weight:Number(m.area_weight||1),frequency:m.frequency})),markerTags:ms.map(m=>m.marker_tag),settings:v.settings||{},notes:v.notes||'',isStructured:!!v.is_structured});});return(designs||[]).map(d=>({id:`cloud_${d.id}`,cloudId:d.id,name:d.name,slug:d.slug,status:d.status,sourceType:d.source_type,legacyCloudinaryUrl:d.legacy_cloudinary_url||'',metadata:d.metadata||{},createdAt:d.created_at,updatedAt:d.updated_at,versions:(versionsBy.get(d.id)||[]).map(v=>({...v,sourcePreview:v.sourcePreview||d.legacy_cloudinary_url||''}))}));}
async function loadCatalog(){const projects=await loadProjects();return{version:new Date().toISOString(),source:'supabase',products:projects.filter(p=>p.status!=='archived').map(p=>({id:p.slug||p.cloudId,name:p.name,cloudDesignId:p.cloudId,recipes:(p.versions||[]).filter(v=>['approved','applied','validated'].includes(v.status)).map(v=>({id:v.cloudId,name:v.name||'Actual',cloudVersionId:v.cloudId,source:v.source,markers:v.markerTags||[]}))})).filter(p=>p.recipes.length)};}
function compactOptimization(res,catalog,settings){return{schema:1,generatedAt:new Date().toISOString(),settings,summary:{groups:res.groups.length,totalChanges:res.totalChanges,meanDelta:res.meanDelta,maxUsedDelta:res.maxUsedDelta,totalRaw:res.totalRaw},groups:res.groups.map((g,i)=>({group:i+1,stats:{rawConflicts:g.rawConflicts,changes:g.res.changeCount,slots:g.res.slots,meanDelta:g.res.meanChangedDelta,maxDelta:g.res.maxUsedDelta},products:g.designs.map(d=>({productId:d.product.id,productName:d.product.name,cloudDesignId:d.product.cloudDesignId||null,recipeId:d.recipe.id,recipeName:d.recipe.name,cloudVersionId:d.recipe.cloudVersionId||null,originalMarkers:d.recipe.markers,optimizedMarkers:d.outputMarkers,changes:(d.changes||[]).map(c=>({from:c.from,to:c.to,deltaE:c.deltaE,wasConflict:!!d.markers.find(m=>String(m.tag)===String(c.from))?.conflict}))}))}))};}
async function saveOptimization(res,catalog,settings){requireAdmin();if(!res?.ok)return null;const payload=compactOptimization(res,catalog,settings),{data:run,error:re}=await client.from('pbn_optimization_runs').insert({mode:'optimizer2_global',status:'completed',settings,summary:payload.summary,result:payload}).select().single();if(re)throw re;for(let gi=0;gi<res.groups.length;gi++){const g=res.groups[gi],{data:k,error:ke}=await client.from('pbn_cases').insert({name:`Estuche ${gi+1} · ${new Date().toLocaleDateString('es-CL')}`,optimization_run_id:run.id,status:'draft',capacity:Number(settings.groupSize||10),metadata:{rawConflicts:g.rawConflicts,changes:g.res.changeCount,slots:g.res.slots}}).select().single();if(ke)throw ke;const items=[];for(let di=0;di<g.designs.length;di++){const d=g.designs[di];if(d.recipe.cloudVersionId)items.push({case_id:k.id,version_id:d.recipe.cloudVersionId,position:di});for(const c of d.changes||[]){if(!d.product.cloudDesignId||!d.recipe.cloudVersionId)continue;const mm=d.markers.find(m=>String(m.tag)===String(c.from));const {error:ce}=await client.from('pbn_optimization_changes').insert({optimization_run_id:run.id,design_id:d.product.cloudDesignId,base_version_id:d.recipe.cloudVersionId,from_marker:String(c.from),to_marker:String(c.to),delta_e:c.deltaE,was_conflict:!!mm?.conflict,strategic_move:!mm?.conflict,metadata:{group:gi+1}});if(ce)throw ce;}}if(items.length){const {error:ie}=await client.from('pbn_case_items').insert(items);if(ie)throw ie;}}
return run.id;}
async function signedUrl(path,seconds=3600){requireAdmin();if(!path)return'';const {data,error}=await client.storage.from(BUCKET).createSignedUrl(path,seconds);if(error)throw error;return data.signedUrl;}
root.PBNCloud={URL,BUCKET,client,init,onSession,session,admin,refreshAdmin,claimAdmin,signUp,signIn,signOut,mountAuth,seedPalette,syncProject,deleteCloudProject,loadProjects,loadCatalog,saveOptimization,compactOptimization,signedUrl,slug};
init().catch(e=>console.warn('PBN cloud init',e));
})(window);